<a href="https://colab.research.google.com/github/mestesf2026/toyotadrive-data-platform/blob/main/ToyotaDrive_Data_Engineering_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("ToyotaDrive Data Engineering Project")
print("Google Colab is working!")

ToyotaDrive Data Engineering Project
Google Colab is working!

In [ ]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.2.2

In [ ]:
!git clone https://github.com/mestesf2026/toyotadrive-data-platform.git

Cloning into 'toyotadrive-data-platform'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 106 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (106/106), 18.54 KiB | 949.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.

In [ ]:
!ls toyotadrive-data-platform

README.md  requirements.txt  run_pipeline.py  src

In [ ]:
!pip install -q -r toyotadrive-data-platform/requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 46.8 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import requests
import sqlalchemy
import pyarrow
import pytest

print("All required libraries are installed successfully!")

All required libraries are installed successfully!

In [ ]:
import os

base = "/content/toyotadrive-data-platform"

folders = [
    "data/raw/sales",
    "data/raw/repairs",
    "data/raw/vehicles",
    "data/raw/dealers",
    "data/raw/economic",
    "data/processed/sales",
    "data/processed/repairs",
    "data/processed/vehicles",
    "data/processed/dealers",
    "data/processed/economic",
    "data/sample"
]

for folder in folders:
    os.makedirs(os.path.join(base, folder), exist_ok=True)

print("Data Lake folders created successfully!")

Data Lake folders created successfully!

In [ ]:
!find toyotadrive-data-platform/data -type d

toyotadrive-data-platform/data
toyotadrive-data-platform/data/raw
toyotadrive-data-platform/data/raw/repairs
toyotadrive-data-platform/data/raw/vehicles
toyotadrive-data-platform/data/raw/dealers
toyotadrive-data-platform/data/raw/economic
toyotadrive-data-platform/data/raw/sales
toyotadrive-data-platform/data/processed
toyotadrive-data-platform/data/processed/repairs
toyotadrive-data-platform/data/processed/vehicles
toyotadrive-data-platform/data/processed/dealers
toyotadrive-data-platform/data/processed/economic
toyotadrive-data-platform/data/processed/sales
toyotadrive-data-platform/data/sample

In [ ]:
import pandas as pd
import os

url = "https://raw.githubusercontent.com/ccfd/courses_data/refs/heads/stat1/cars.csv"

sales_df = pd.read_csv(url)

print("Sales data downloaded successfully!")
print("Rows:", len(sales_df))
print("Columns:", len(sales_df.columns))

sales_df.head()

Sales data downloaded successfully!
Rows: 402928
Columns: 15

,year,make,model,body,transmission,vin,state,condition,odometer,color,interior,mmr,sellingprice,saledate,truck
0,2015,Kia,Sorento,SUV,automatic,5xyktca69fg566472,CA,5.0,16639.0,white,black,20500,21500,2014-12-16 12:30:00,False
1,2015,Kia,Sorento,SUV,automatic,5xyktca69fg561319,CA,5.0,9393.0,white,beige,20800,21500,2014-12-16 12:30:00,False
2,2014,BMW,3 Series,Sedan,automatic,wba3c1c51ek116351,CA,45.0,1331.0,gray,black,31900,30000,2015-01-15 04:30:00,False
3,2015,Volvo,S60,Sedan,automatic,yv1612tb4f1310987,CA,41.0,14282.0,white,black,27500,27750,2015-01-29 04:30:00,False
4,2014,BMW,6 Series Gran Coupe,Sedan,automatic,wba6b2c57ed129731,CA,43.0,2641.0,gray,black,66000,67000,2014-12-18 12:30:00,False

In [ ]:
raw_sales_path = "/content/toyotadrive-data-platform/data/raw/sales/sales_raw.csv"

sales_df.to_csv(raw_sales_path, index=False)

print("Sales data saved to:")
print(raw_sales_path)

Sales data saved to:
/content/toyotadrive-data-platform/data/raw/sales/sales_raw.csv

In [ ]:
import os

print(os.path.exists(raw_sales_path))
print(os.path.getsize(raw_sales_path), "bytes")

True
46965725 bytes

In [ ]:
import pandas as pd

repair_url = "https://raw.githubusercontent.com/"

print("We are preparing the repair-data source.")

We are preparing the repair-data source.

In [ ]:
import pandas as pd

print("Repair data step is ready.")

Repair data step is ready.

In [ ]:
repair_url = "https://raw.githubusercontent.com/IBM/employee-attrition-aif360/master/data/repair.csv"

In [ ]:
repair_url = "https://raw.githubusercontent.com/IBM/employee-attrition-aif360/master/data/repair.csv"

In [ ]:
import pandas as pd

repair_url = "https://gist.githubusercontent.com/amattu2/e4e6be2e6114c2229c8647fa282c1a3a/raw/dataset.csv"

repairs_df = pd.read_csv(repair_url)

print("Repair data downloaded successfully!")
print("Rows:", len(repairs_df))
print("Columns:", len(repairs_df.columns))

display(repairs_df.head())

Repair data downloaded successfully!
Rows: 1
Columns: 7

,Date,TicketType,Total,Mileage,ModYear,Make,Model
0,2002-10-31 08:59:00,Invoice,5.0,37032,2001,DODGE,CARAVAN -GRAND CARAVAN

In [ ]:
import os

# Location of the repair data in our Data Lake
repair_path = "/content/toyotadrive-data-platform/data/raw/repairs/repairs_raw.csv"

# Make sure the folder exists
os.makedirs(
    "/content/toyotadrive-data-platform/data/raw/repairs",
    exist_ok=True
)

# Save the raw repair data
repairs_df.to_csv(repair_path, index=False)

print("Repair data saved successfully!")
print("Location:", repair_path)

Repair data saved successfully!
Location: /content/toyotadrive-data-platform/data/raw/repairs/repairs_raw.csv

In [ ]:
import os

print("File exists:", os.path.exists(repair_path))

if os.path.exists(repair_path):
    print("File size:", os.path.getsize(repair_path), "bytes")

File exists: True
File size: 121 bytes

In [ ]:
import requests
import json
import os

# NHTSA vPIC API
url = "https://vpic.nhtsa.dot.gov/api/vehicles/GetModelsForMakeId/440?format=json"

response = requests.get(url, timeout=30)

print("HTTP status:", response.status_code)

response.raise_for_status()

vehicle_data = response.json()

print("Vehicle API data downloaded successfully!")
print("Number of vehicle records:", len(vehicle_data["Results"]))

print("\nFirst 5 records:")
for record in vehicle_data["Results"][:5]:
    print(record)

HTTP status: 200
Vehicle API data downloaded successfully!
Number of vehicle records: 18

First 5 records:
{'Make_ID': 440, 'Make_Name': 'Aston Martin', 'Model_ID': 1684, 'Model_Name': 'V8 Vantage'}
{'Make_ID': 440, 'Make_Name': 'Aston Martin', 'Model_ID': 1686, 'Model_Name': 'DBS'}
{'Make_ID': 440, 'Make_Name': 'Aston Martin', 'Model_ID': 1687, 'Model_Name': 'DB9'}
{'Make_ID': 440, 'Make_Name': 'Aston Martin', 'Model_ID': 1688, 'Model_Name': 'Rapide'}
{'Make_ID': 440, 'Make_Name': 'Aston Martin', 'Model_ID': 1695, 'Model_Name': 'V12 Vantage'}

In [ ]:
import json
import os

# Location in our Data Lake
vehicle_path = "/content/toyotadrive-data-platform/data/raw/vehicles/vehicles_raw.json"

# Make sure the folder exists
os.makedirs(
    "/content/toyotadrive-data-platform/data/raw/vehicles",
    exist_ok=True
)

# Save the complete API response as raw JSON
with open(vehicle_path, "w", encoding="utf-8") as f:
    json.dump(vehicle_data, f, indent=2)

print("Vehicle API data saved successfully!")
print("Location:", vehicle_path)

Vehicle API data saved successfully!
Location: /content/toyotadrive-data-platform/data/raw/vehicles/vehicles_raw.json

In [ ]:
import os

print("File exists:", os.path.exists(vehicle_path))

if os.path.exists(vehicle_path):
    print("File size:", os.path.getsize(vehicle_path), "bytes")

File exists: True
File size: 2347 bytes

In [ ]:
import pandas as pd

print("Dealer data step is ready.")

Dealer data step is ready.

In [ ]:
print("Dealer data step is ready.")

Dealer data step is ready.

In [ ]:
import pandas as pd

dealer_url = "https://raw.githubusercontent.com/rebrowser/carscom-dataset/main/car-listings/sample.csv"

try:
    dealers_df = pd.read_csv(dealer_url)

    print("Dealer data downloaded successfully!")
    print("Rows:", len(dealers_df))
    print("Columns:", len(dealers_df.columns))

    display(dealers_df.head())

except Exception as e:
    print("The download URL could not be accessed.")
    print("Error:", e)

The download URL could not be accessed.
Error: HTTP Error 404: Not Found

In [ ]:
import pandas as pd
import os

# Synthetic dealer data for the ToyotaDrive portfolio project
dealers_df = pd.DataFrame({
    "dealer_id": ["D001", "D002", "D003", "D004", "D005"],
    "dealer_name": [
        "ToyotaDrive Washington",
        "ToyotaDrive Arlington",
        "ToyotaDrive Alexandria",
        "ToyotaDrive Bethesda",
        "ToyotaDrive Silver Spring"
    ],
    "city": [
        "Washington",
        "Arlington",
        "Alexandria",
        "Bethesda",
        "Silver Spring"
    ],
    "state": [
        "DC",
        "VA",
        "VA",
        "MD",
        "MD"
    ],
    "country": [
        "USA",
        "USA",
        "USA",
        "USA",
        "USA"
    ],
    "service_department": [
        True,
        True,
        True,
        True,
        True
    ]
})

print("Dealer data created successfully!")

display(dealers_df)

Dealer data created successfully!

,dealer_id,dealer_name,city,state,country,service_department
0,D001,ToyotaDrive Washington,Washington,DC,USA,True
1,D002,ToyotaDrive Arlington,Arlington,VA,USA,True
2,D003,ToyotaDrive Alexandria,Alexandria,VA,USA,True
3,D004,ToyotaDrive Bethesda,Bethesda,MD,USA,True
4,D005,ToyotaDrive Silver Spring,Silver Spring,MD,USA,True

In [ ]:
import os

# Location of dealer data in the Data Lake
dealer_path = "/content/toyotadrive-data-platform/data/raw/dealers/dealers_raw.csv"

# Make sure the folder exists
os.makedirs(
    "/content/toyotadrive-data-platform/data/raw/dealers",
    exist_ok=True
)

# Save dealer data
dealers_df.to_csv(dealer_path, index=False)

print("Dealer data saved successfully!")
print("Location:", dealer_path)

Dealer data saved successfully!
Location: /content/toyotadrive-data-platform/data/raw/dealers/dealers_raw.csv

In [ ]:
import os

print("File exists:", os.path.exists(dealer_path))

if os.path.exists(dealer_path):
    print("File size:", os.path.getsize(dealer_path), "bytes")

File exists: True
File size: 315 bytes

In [ ]:
import pandas as pd

# FRED unemployment rate data
economic_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=UNRATE"

economic_df = pd.read_csv(economic_url)

print("Economic data downloaded successfully!")
print("Rows:", len(economic_df))
print("Columns:", len(economic_df.columns))

display(economic_df.head())

Economic data downloaded successfully!
Rows: 943
Columns: 2

  observation_date  UNRATE
0       1948-01-01     3.4
1       1948-02-01     3.8
2       1948-03-01     4.0
3       1948-04-01     3.9
4       1948-05-01     3.5

In [ ]:
import os

# Location of economic data in the Data Lake
economic_path = "/content/toyotadrive-data-platform/data/raw/economic/economic_raw.csv"

# Make sure the folder exists
os.makedirs(
    "/content/toyotadrive-data-platform/data/raw/economic",
    exist_ok=True
)

# Save the raw economic data
economic_df.to_csv(economic_path, index=False)

print("Economic data saved successfully!")
print("Location:", economic_path)

Economic data saved successfully!
Location: /content/toyotadrive-data-platform/data/raw/economic/economic_raw.csv

In [ ]:
import os

print("File exists:", os.path.exists(economic_path))

if os.path.exists(economic_path):
    print("File size:", os.path.getsize(economic_path), "bytes")

File exists: True
File size: 14181 bytes

In [ ]:
import os
import pandas as pd
import json

base = "/content/toyotadrive-data-platform/data/raw"

# File locations
files = {
    "Sales": f"{base}/sales/sales_raw.csv",
    "Repairs": f"{base}/repairs/repairs_raw.csv",
    "Vehicles": f"{base}/vehicles/vehicles_raw.json",
    "Dealers": f"{base}/dealers/dealers_raw.csv",
    "Economic": f"{base}/economic/economic_raw.csv"
}

print("===== RAW DATA VALIDATION =====\n")

for name, path in files.items():
    print(f"{name}:")

    if os.path.exists(path):
        print("  File exists: YES")
        print(f"  File size: {os.path.getsize(path):,} bytes")

        if path.endswith(".csv"):
            df = pd.read_csv(path)
            print(f"  Rows: {len(df):,}")
            print(f"  Columns: {len(df.columns)}")
            print(f"  Column names: {list(df.columns)}")

        elif path.endswith(".json"):
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)

            print(f"  JSON records: {len(data.get('Results', [])):,}")

    else:
        print("  File exists: NO")

    print()

===== RAW DATA VALIDATION =====

Sales:
  File exists: YES
  File size: 46,965,725 bytes
  Rows: 402,928
  Columns: 15
  Column names: ['year', 'make', 'model', 'body', 'transmission', 'vin', 'state', 'condition', 'odometer', 'color', 'interior', 'mmr', 'sellingprice', 'saledate', 'truck']

Repairs:
  File exists: YES
  File size: 121 bytes
  Rows: 1
  Columns: 7
  Column names: ['Date', 'TicketType', 'Total', 'Mileage', 'ModYear', 'Make', 'Model']

Vehicles:
  File exists: YES
  File size: 2,347 bytes
  JSON records: 18

Dealers:
  File exists: YES
  File size: 315 bytes
  Rows: 5
  Columns: 6
  Column names: ['dealer_id', 'dealer_name', 'city', 'state', 'country', 'service_department']

Economic:
  File exists: YES
  File size: 14,181 bytes
  Rows: 943
  Columns: 2
  Column names: ['observation_date', 'UNRATE']

In [ ]:
# Inspect the Sales Data
import pandas as pd

sales_path = "/content/toyotadrive-data-platform/data/raw/sales/sales_raw.csv"

sales_df = pd.read_csv(sales_path)

print("Sales dataset loaded successfully!")
print("\nShape:")
print(sales_df.shape)

print("\nColumns:")
print(list(sales_df.columns))

print("\nData types:")
print(sales_df.dtypes)

print("\nFirst 5 records:")
display(sales_df.head())

print("\nMissing values:")
print(sales_df.isnull().sum())

Sales dataset loaded successfully!

Shape:
(402928, 15)

Columns:
['year', 'make', 'model', 'body', 'transmission', 'vin', 'state', 'condition', 'odometer', 'color', 'interior', 'mmr', 'sellingprice', 'saledate', 'truck']

Data types:
year              int64
make             object
model            object
body             object
transmission     object
vin              object
state            object
condition       float64
odometer        float64
color            object
interior         object
mmr               int64
sellingprice      int64
saledate         object
truck            object
dtype: object

First 5 records:

,year,make,model,body,transmission,vin,state,condition,odometer,color,interior,mmr,sellingprice,saledate,truck
0,2015,Kia,Sorento,SUV,automatic,5xyktca69fg566472,CA,5.0,16639.0,white,black,20500,21500,2014-12-16 12:30:00,False
1,2015,Kia,Sorento,SUV,automatic,5xyktca69fg561319,CA,5.0,9393.0,white,beige,20800,21500,2014-12-16 12:30:00,False
2,2014,BMW,3 Series,Sedan,automatic,wba3c1c51ek116351,CA,45.0,1331.0,gray,black,31900,30000,2015-01-15 04:30:00,False
3,2015,Volvo,S60,Sedan,automatic,yv1612tb4f1310987,CA,41.0,14282.0,white,black,27500,27750,2015-01-29 04:30:00,False
4,2014,BMW,6 Series Gran Coupe,Sedan,automatic,wba6b2c57ed129731,CA,43.0,2641.0,gray,black,66000,67000,2014-12-18 12:30:00,False

Missing values:
year                0
make             7167
model            7231
body            10034
transmission    44193
vin                 0
state               0
condition       11793
odometer          134
color           18321
interior        14285
mmr                 0
sellingprice        0
saledate            0
truck            7167
dtype: int64

In [ ]:
#Clean Sales Data
import pandas as pd
import os

# Load raw sales data
sales_path = "/content/toyotadrive-data-platform/data/raw/sales/sales_raw.csv"
sales_df = pd.read_csv(sales_path)

print("Raw sales rows:", len(sales_df))

# -----------------------------
# 1. Standardize column names
# -----------------------------
sales_df.columns = (
    sales_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# -----------------------------
# 2. Remove completely empty rows
# -----------------------------
sales_df = sales_df.dropna(how="all")

# -----------------------------
# 3. Remove duplicate records
# -----------------------------
sales_df = sales_df.drop_duplicates()

# -----------------------------
# 4. Convert sale date
# -----------------------------
if "saledate" in sales_df.columns:
    sales_df["saledate"] = pd.to_datetime(
        sales_df["saledate"],
        errors="coerce"
    )

# -----------------------------
# 5. Clean selling price
# -----------------------------
if "sellingprice" in sales_df.columns:
    sales_df["sellingprice"] = pd.to_numeric(
        sales_df["sellingprice"],
        errors="coerce"
    )

# -----------------------------
# 6. Clean odometer
# -----------------------------
if "odometer" in sales_df.columns:
    sales_df["odometer"] = pd.to_numeric(
        sales_df["odometer"],
        errors="coerce"
    )

# -----------------------------
# 7. Standardize text columns
# -----------------------------
text_columns = sales_df.select_dtypes(
    include=["object"]
).columns

for column in text_columns:
    sales_df[column] = (
        sales_df[column]
        .astype("string")
        .str.strip()
    )

# -----------------------------
# 8. Remove impossible prices
# -----------------------------
if "sellingprice" in sales_df.columns:
    sales_df = sales_df[
        sales_df["sellingprice"].notna()
        & (sales_df["sellingprice"] > 0)
    ]

# -----------------------------
# 9. Remove impossible mileage
# -----------------------------
if "odometer" in sales_df.columns:
    sales_df = sales_df[
        sales_df["odometer"].isna()
        | (sales_df["odometer"] >= 0)
    ]

# -----------------------------
# 10. Save processed sales data
# -----------------------------
processed_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/sales/sales_clean.csv"
)

os.makedirs(
    "/content/toyotadrive-data-platform/data/processed/sales",
    exist_ok=True
)

sales_df.to_csv(processed_path, index=False)

# -----------------------------
# 11. Display results
# -----------------------------
print("\nSales transformation completed!")
print("Processed rows:", len(sales_df))
print("Processed columns:", len(sales_df.columns))
print("Saved to:", processed_path)

display(sales_df.head())

Raw sales rows: 402928

Sales transformation completed!
Processed rows: 402928
Processed columns: 15
Saved to: /content/toyotadrive-data-platform/data/processed/sales/sales_clean.csv

,year,make,model,body,transmission,vin,state,condition,odometer,color,interior,mmr,sellingprice,saledate,truck
0,2015,Kia,Sorento,SUV,automatic,5xyktca69fg566472,CA,5.0,16639.0,white,black,20500,21500,2014-12-16 12:30:00,False
1,2015,Kia,Sorento,SUV,automatic,5xyktca69fg561319,CA,5.0,9393.0,white,beige,20800,21500,2014-12-16 12:30:00,False
2,2014,BMW,3 Series,Sedan,automatic,wba3c1c51ek116351,CA,45.0,1331.0,gray,black,31900,30000,2015-01-15 04:30:00,False
3,2015,Volvo,S60,Sedan,automatic,yv1612tb4f1310987,CA,41.0,14282.0,white,black,27500,27750,2015-01-29 04:30:00,False
4,2014,BMW,6 Series Gran Coupe,Sedan,automatic,wba6b2c57ed129731,CA,43.0,2641.0,gray,black,66000,67000,2014-12-18 12:30:00,False

In [ ]:
import pandas as pd
import os

# Load raw repair data
repair_path = "/content/toyotadrive-data-platform/data/raw/repairs/repairs_raw.csv"

repairs_df = pd.read_csv(repair_path)

print("Raw repair rows:", len(repairs_df))
print("Original columns:", list(repairs_df.columns))

# --------------------------------
# 1. Standardize column names
# --------------------------------
repairs_df.columns = (
    repairs_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# --------------------------------
# 2. Remove completely empty rows
# --------------------------------
repairs_df = repairs_df.dropna(how="all")

# --------------------------------
# 3. Remove duplicate records
# --------------------------------
repairs_df = repairs_df.drop_duplicates()

# --------------------------------
# 4. Convert date column if present
# --------------------------------
date_columns = [
    "date",
    "service_date",
    "repair_date"
]

for column in date_columns:
    if column in repairs_df.columns:
        repairs_df[column] = pd.to_datetime(
            repairs_df[column],
            errors="coerce"
        )

# --------------------------------
# 5. Clean numeric columns
# --------------------------------
numeric_columns = [
    "total",
    "cost",
    "price",
    "mileage",
    "odometer"
]

for column in numeric_columns:
    if column in repairs_df.columns:
        repairs_df[column] = pd.to_numeric(
            repairs_df[column],
            errors="coerce"
        )

# --------------------------------
# 6. Standardize text columns
# --------------------------------
text_columns = repairs_df.select_dtypes(
    include=["object"]
).columns

for column in text_columns:
    repairs_df[column] = (
        repairs_df[column]
        .astype("string")
        .str.strip()
    )

# --------------------------------
# 7. Remove impossible mileage
# --------------------------------
for column in ["mileage", "odometer"]:
    if column in repairs_df.columns:
        repairs_df = repairs_df[
            repairs_df[column].isna()
            | (repairs_df[column] >= 0)
        ]

# --------------------------------
# 8. Remove impossible repair cost
# --------------------------------
for column in ["total", "cost", "price"]:
    if column in repairs_df.columns:
        repairs_df = repairs_df[
            repairs_df[column].isna()
            | (repairs_df[column] >= 0)
        ]

# --------------------------------
# 9. Save processed repair data
# --------------------------------
processed_repair_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/repairs/repairs_clean.csv"
)

os.makedirs(
    "/content/toyotadrive-data-platform/data/processed/repairs",
    exist_ok=True
)

repairs_df.to_csv(
    processed_repair_path,
    index=False
)

print("\nRepair transformation completed!")
print("Processed rows:", len(repairs_df))
print("Processed columns:", len(repairs_df.columns))
print("Saved to:", processed_repair_path)

display(repairs_df.head())

Raw repair rows: 1
Original columns: ['Date', 'TicketType', 'Total', 'Mileage', 'ModYear', 'Make', 'Model']

Repair transformation completed!
Processed rows: 1
Processed columns: 7
Saved to: /content/toyotadrive-data-platform/data/processed/repairs/repairs_clean.csv

,date,tickettype,total,mileage,modyear,make,model
0,2002-10-31 08:59:00,Invoice,5.0,37032,2001,DODGE,CARAVAN -GRAND CARAVAN

In [ ]:
import os

print(
    "Processed repair file exists:",
    os.path.exists(processed_repair_path)
)

if os.path.exists(processed_repair_path):
    print(
        "File size:",
        os.path.getsize(processed_repair_path),
        "bytes"
    )

Processed repair file exists: True
File size: 121 bytes

In [ ]:
import pandas as pd
import json
import os

# --------------------------------
# 1. Load raw vehicle JSON
# --------------------------------
vehicle_path = (
    "/content/toyotadrive-data-platform/"
    "data/raw/vehicles/vehicles_raw.json"
)

with open(vehicle_path, "r", encoding="utf-8") as f:
    vehicle_data = json.load(f)

# Extract API results
vehicle_records = vehicle_data.get("Results", [])

vehicles_df = pd.DataFrame(vehicle_records)

print("Raw vehicle records:", len(vehicles_df))
print("Original columns:", list(vehicles_df.columns))

# --------------------------------
# 2. Standardize column names
# --------------------------------
vehicles_df.columns = (
    vehicles_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# --------------------------------
# 3. Remove empty rows
# --------------------------------
vehicles_df = vehicles_df.dropna(how="all")

# --------------------------------
# 4. Remove duplicate vehicles
# --------------------------------
vehicles_df = vehicles_df.drop_duplicates()

# --------------------------------
# 5. Clean text columns
# --------------------------------
text_columns = vehicles_df.select_dtypes(
    include=["object"]
).columns

for column in text_columns:
    vehicles_df[column] = (
        vehicles_df[column]
        .astype("string")
        .str.strip()
    )

# --------------------------------
# 6. Save processed vehicle data
# --------------------------------
processed_vehicle_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/vehicles/vehicles_clean.csv"
)

os.makedirs(
    "/content/toyotadrive-data-platform/data/processed/vehicles",
    exist_ok=True
)

vehicles_df.to_csv(
    processed_vehicle_path,
    index=False
)

print("\nVehicle transformation completed!")
print("Processed records:", len(vehicles_df))
print("Processed columns:", len(vehicles_df.columns))
print("Saved to:", processed_vehicle_path)

display(vehicles_df.head())

Raw vehicle records: 18
Original columns: ['Make_ID', 'Make_Name', 'Model_ID', 'Model_Name']

Vehicle transformation completed!
Processed records: 18
Processed columns: 4
Saved to: /content/toyotadrive-data-platform/data/processed/vehicles/vehicles_clean.csv

   make_id     make_name  model_id   model_name
0      440  Aston Martin      1684   V8 Vantage
1      440  Aston Martin      1686          DBS
2      440  Aston Martin      1687          DB9
3      440  Aston Martin      1688       Rapide
4      440  Aston Martin      1695  V12 Vantage

In [ ]:
import os

print(
    "Processed vehicle file exists:",
    os.path.exists(processed_vehicle_path)
)

if os.path.exists(processed_vehicle_path):
    print(
        "File size:",
        os.path.getsize(processed_vehicle_path),
        "bytes"
    )

Processed vehicle file exists: True
File size: 576 bytes

In [ ]:
import pandas as pd
import os

# --------------------------------
# 1. Load raw dealer data
# --------------------------------
dealer_path = (
    "/content/toyotadrive-data-platform/"
    "data/raw/dealers/dealers_raw.csv"
)

dealers_df = pd.read_csv(dealer_path)

print("Raw dealer rows:", len(dealers_df))
print("Original columns:", list(dealers_df.columns))

# --------------------------------
# 2. Standardize column names
# --------------------------------
dealers_df.columns = (
    dealers_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# --------------------------------
# 3. Remove completely empty rows
# --------------------------------
dealers_df = dealers_df.dropna(how="all")

# --------------------------------
# 4. Remove duplicates
# --------------------------------
dealers_df = dealers_df.drop_duplicates()

# --------------------------------
# 5. Clean text columns
# --------------------------------
text_columns = dealers_df.select_dtypes(
    include=["object"]
).columns

for column in text_columns:
    dealers_df[column] = (
        dealers_df[column]
        .astype("string")
        .str.strip()
    )

# --------------------------------
# 6. Standardize service flag
# --------------------------------
if "service_department" in dealers_df.columns:
    dealers_df["service_department"] = (
        dealers_df["service_department"]
        .astype(bool)
    )

# --------------------------------
# 7. Validate dealer IDs
# --------------------------------
if "dealer_id" in dealers_df.columns:
    dealers_df = dealers_df[
        dealers_df["dealer_id"].notna()
    ]

# --------------------------------
# 8. Save processed dealer data
# --------------------------------
processed_dealer_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/dealers/dealers_clean.csv"
)

os.makedirs(
    "/content/toyotadrive-data-platform/data/processed/dealers",
    exist_ok=True
)

dealers_df.to_csv(
    processed_dealer_path,
    index=False
)

print("\nDealer transformation completed!")
print("Processed rows:", len(dealers_df))
print("Processed columns:", len(dealers_df.columns))
print("Saved to:", processed_dealer_path)

display(dealers_df)

Raw dealer rows: 5
Original columns: ['dealer_id', 'dealer_name', 'city', 'state', 'country', 'service_department']

Dealer transformation completed!
Processed rows: 5
Processed columns: 6
Saved to: /content/toyotadrive-data-platform/data/processed/dealers/dealers_clean.csv

,dealer_id,dealer_name,city,state,country,service_department
0,D001,ToyotaDrive Washington,Washington,DC,USA,True
1,D002,ToyotaDrive Arlington,Arlington,VA,USA,True
2,D003,ToyotaDrive Alexandria,Alexandria,VA,USA,True
3,D004,ToyotaDrive Bethesda,Bethesda,MD,USA,True
4,D005,ToyotaDrive Silver Spring,Silver Spring,MD,USA,True

In [ ]:
import os

print(
    "Processed dealer file exists:",
    os.path.exists(processed_dealer_path)
)

if os.path.exists(processed_dealer_path):
    print(
        "File size:",
        os.path.getsize(processed_dealer_path),
        "bytes"
    )

Processed dealer file exists: True
File size: 315 bytes

In [ ]:
import pandas as pd
import os

# --------------------------------
# 1. Load raw economic data
# --------------------------------
economic_path = (
    "/content/toyotadrive-data-platform/"
    "data/raw/economic/economic_raw.csv"
)

economic_df = pd.read_csv(economic_path)

print("Raw economic rows:", len(economic_df))
print("Original columns:", list(economic_df.columns))

# --------------------------------
# 2. Standardize column names
# --------------------------------
economic_df.columns = (
    economic_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# --------------------------------
# 3. Convert date
# --------------------------------
if "date" in economic_df.columns:
    economic_df["date"] = pd.to_datetime(
        economic_df["date"],
        errors="coerce"
    )

# FRED may use "observation_date"
elif "observation_date" in economic_df.columns:
    economic_df["observation_date"] = pd.to_datetime(
        economic_df["observation_date"],
        errors="coerce"
    )

# --------------------------------
# 4. Convert unemployment rate
# --------------------------------
if "unrate" in economic_df.columns:
    economic_df["unrate"] = pd.to_numeric(
        economic_df["unrate"],
        errors="coerce"
    )

# --------------------------------
# 5. Remove empty rows
# --------------------------------
economic_df = economic_df.dropna(how="all")

# --------------------------------
# 6. Remove duplicate records
# --------------------------------
economic_df = economic_df.drop_duplicates()

# --------------------------------
# 7. Remove invalid unemployment rates
# --------------------------------
if "unrate" in economic_df.columns:
    economic_df = economic_df[
        economic_df["unrate"].notna()
        & (economic_df["unrate"] >= 0)
    ]

# --------------------------------
# 8. Save processed economic data
# --------------------------------
processed_economic_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/economic/economic_clean.csv"
)

os.makedirs(
    "/content/toyotadrive-data-platform/"
    "data/processed/economic",
    exist_ok=True
)

economic_df.to_csv(
    processed_economic_path,
    index=False
)

print("\nEconomic transformation completed!")
print("Processed rows:", len(economic_df))
print("Processed columns:", len(economic_df.columns))
print("Saved to:", processed_economic_path)

display(economic_df.head())

Raw economic rows: 943
Original columns: ['observation_date', 'UNRATE']

Economic transformation completed!
Processed rows: 942
Processed columns: 2
Saved to: /content/toyotadrive-data-platform/data/processed/economic/economic_clean.csv

  observation_date  unrate
0       1948-01-01     3.4
1       1948-02-01     3.8
2       1948-03-01     4.0
3       1948-04-01     3.9
4       1948-05-01     3.5

In [ ]:
import os

print(
    "Processed economic file exists:",
    os.path.exists(processed_economic_path)
)

if os.path.exists(processed_economic_path):
    print(
        "File size:",
        os.path.getsize(processed_economic_path),
        "bytes"
    )

Processed economic file exists: True
File size: 14169 bytes

In [ ]:
!pip -q install psycopg2-binary

In [ ]:
import os

print("Secret available:", "NEON_DATABASE_URL" in os.environ)

Secret available: False

In [ ]:
from google.colab import userdata

database_url = userdata.get("NEON_DATABASE_URL")

print("Secret found:", database_url is not None)

Secret found: True

In [ ]:
from google.colab import userdata
import psycopg2

# Get the Neon connection string securely
database_url = userdata.get("NEON_DATABASE_URL")

try:
    conn = psycopg2.connect(database_url)

    print("Successfully connected to Neon PostgreSQL!")

    conn.close()

except Exception as e:
    print("Connection failed.")
    print("Error:", e)

Successfully connected to Neon PostgreSQL!

In [ ]:
from google.colab import userdata
import psycopg2

# Get Neon connection securely
database_url = userdata.get("NEON_DATABASE_URL")

# Connect to PostgreSQL
conn = psycopg2.connect(database_url)
cursor = conn.cursor()

# Warehouse schema
schema_sql = """

CREATE TABLE IF NOT EXISTS dim_dealer (
    dealer_key SERIAL PRIMARY KEY,
    dealer_id VARCHAR(20) UNIQUE NOT NULL,
    dealer_name VARCHAR(150),
    city VARCHAR(100),
    state VARCHAR(50),
    country VARCHAR(50),
    service_department BOOLEAN
);

CREATE TABLE IF NOT EXISTS dim_vehicle (
    vehicle_key SERIAL PRIMARY KEY,
    vehicle_id VARCHAR(100),
    make VARCHAR(100),
    model VARCHAR(100),
    model_year INTEGER,
    vehicle_type VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    year INTEGER,
    quarter INTEGER,
    month INTEGER,
    month_name VARCHAR(20),
    day INTEGER
);

CREATE TABLE IF NOT EXISTS dim_economic (
    economic_key SERIAL PRIMARY KEY,
    economic_date DATE,
    unemployment_rate DECIMAL(5,2)
);

CREATE TABLE IF NOT EXISTS fact_sales (
    sales_key SERIAL PRIMARY KEY,
    dealer_key INTEGER,
    vehicle_key INTEGER,
    date_key INTEGER,
    selling_price DECIMAL(12,2),
    odometer INTEGER,

    FOREIGN KEY (dealer_key)
        REFERENCES dim_dealer(dealer_key),

    FOREIGN KEY (vehicle_key)
        REFERENCES dim_vehicle(vehicle_key),

    FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key)
);

CREATE TABLE IF NOT EXISTS fact_repairs (
    repair_key SERIAL PRIMARY KEY,
    dealer_key INTEGER,
    vehicle_key INTEGER,
    repair_date DATE,
    repair_cost DECIMAL(12,2),
    mileage INTEGER,

    FOREIGN KEY (dealer_key)
        REFERENCES dim_dealer(dealer_key),

    FOREIGN KEY (vehicle_key)
        REFERENCES dim_vehicle(vehicle_key)
);

"""

# Execute schema
cursor.execute(schema_sql)

# Save changes
conn.commit()

print("Warehouse tables created successfully!")

# Close connection
cursor.close()
conn.close()

Warehouse tables created successfully!

In [ ]:
from google.colab import userdata
import psycopg2

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()

cursor.execute("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_name;
""")

tables = cursor.fetchall()

print("Tables in the warehouse:\n")

for table in tables:
    print("-", table[0])

cursor.close()
conn.close()

Tables in the warehouse:

- dim_date
- dim_dealer
- dim_economic
- dim_vehicle
- fact_repairs
- fact_sales

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

# ---------------------------------------
# 1. Load processed dealer data
# ---------------------------------------
dealer_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/dealers/dealers_clean.csv"
)

dealers_df = pd.read_csv(dealer_path)

print("Dealer records to load:", len(dealers_df))

# ---------------------------------------
# 2. Connect to Neon
# ---------------------------------------
database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()

# ---------------------------------------
# 3. Insert dealer records
# ---------------------------------------
insert_sql = """
    INSERT INTO dim_dealer
    (
        dealer_id,
        dealer_name,
        city,
        state,
        country,
        service_department
    )
    VALUES (%s, %s, %s, %s, %s, %s)
    ON CONFLICT (dealer_id) DO NOTHING;
"""

for _, row in dealers_df.iterrows():

    cursor.execute(
        insert_sql,
        (
            row["dealer_id"],
            row["dealer_name"],
            row["city"],
            row["state"],
            row["country"],
            row["service_department"]
        )
    )

# ---------------------------------------
# 4. Save changes
# ---------------------------------------
conn.commit()

print("Dealer data loaded successfully!")

# ---------------------------------------
# 5. Check warehouse
# ---------------------------------------
cursor.execute("""
    SELECT COUNT(*)
    FROM dim_dealer;
""")

count = cursor.fetchone()[0]

print("Rows currently in dim_dealer:", count)

cursor.close()
conn.close()

Dealer records to load: 5
Dealer data loaded successfully!
Rows currently in dim_dealer: 5

In [ ]:
from google.colab import userdata
import psycopg2

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()

cursor.execute("""
    SELECT
        dealer_key,
        dealer_id,
        dealer_name,
        city,
        state,
        service_department
    FROM dim_dealer
    ORDER BY dealer_key;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

cursor.close()
conn.close()

(1, 'D001', 'ToyotaDrive Washington', 'Washington', 'DC', True)
(2, 'D002', 'ToyotaDrive Arlington', 'Arlington', 'VA', True)
(3, 'D003', 'ToyotaDrive Alexandria', 'Alexandria', 'VA', True)
(4, 'D004', 'ToyotaDrive Bethesda', 'Bethesda', 'MD', True)
(5, 'D005', 'ToyotaDrive Silver Spring', 'Silver Spring', 'MD', True)

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

# ---------------------------------------
# 1. Load processed vehicle data
# ---------------------------------------
vehicle_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/vehicles/vehicles_clean.csv"
)

vehicles_df = pd.read_csv(vehicle_path)

print("Vehicle records to load:", len(vehicles_df))
print("Available columns:")
print(list(vehicles_df.columns))


# ---------------------------------------
# 2. Connect to Neon
# ---------------------------------------
database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()


# ---------------------------------------
# 3. Load vehicle records
# ---------------------------------------
insert_sql = """
    INSERT INTO dim_vehicle
    (
        vehicle_id,
        make,
        model,
        model_year,
        vehicle_type
    )
    VALUES (%s, %s, %s, %s, %s);
"""

loaded = 0

for _, row in vehicles_df.iterrows():

    vehicle_id = row.get("model_id")
    make = row.get("make_name")
    model = row.get("model_name")

    cursor.execute(
        insert_sql,
        (
            str(vehicle_id) if pd.notna(vehicle_id) else None,
            str(make) if pd.notna(make) else None,
            str(model) if pd.notna(model) else None,
            None,
            None
        )
    )

    loaded += 1


# ---------------------------------------
# 4. Save changes
# ---------------------------------------
conn.commit()

print("\nVehicle data loaded successfully!")
print("Records inserted:", loaded)


# ---------------------------------------
# 5. Check warehouse
# ---------------------------------------
cursor.execute("""
    SELECT COUNT(*)
    FROM dim_vehicle;
""")

count = cursor.fetchone()[0]

print("Rows currently in dim_vehicle:", count)


cursor.close()
conn.close()

Vehicle records to load: 18
Available columns:
['make_id', 'make_name', 'model_id', 'model_name']

Vehicle data loaded successfully!
Records inserted: 18
Rows currently in dim_vehicle: 18

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

query = """
    SELECT
        vehicle_key,
        vehicle_id,
        make,
        model,
        model_year,
        vehicle_type
    FROM dim_vehicle
    ORDER BY vehicle_key
    LIMIT 10;
"""

vehicles_check = pd.read_sql(query, conn)

display(vehicles_check)

conn.close()

/tmp/ipykernel_770/56338447.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vehicles_check = pd.read_sql(query, conn)

   vehicle_key vehicle_id          make        model model_year vehicle_type
0            1       1684  Aston Martin   V8 Vantage       None         None
1            2       1686  Aston Martin          DBS       None         None
2            3       1687  Aston Martin          DB9       None         None
3            4       1688  Aston Martin       Rapide       None         None
4            5       1695  Aston Martin  V12 Vantage       None         None
5            6       1697  Aston Martin       Virage       None         None
6            7       1701  Aston Martin     Vanquish       None         None
7            8      13751  Aston Martin         DB11       None         None
8            9      14157  Aston Martin      Lagonda       None         None
9           10      14162  Aston Martin      Vantage       None         None

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

# ---------------------------------------
# 1. Load processed economic data
# ---------------------------------------
economic_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/economic/economic_clean.csv"
)

economic_df = pd.read_csv(economic_path)

print("Economic records to load:", len(economic_df))
print("Columns:", list(economic_df.columns))


# ---------------------------------------
# 2. Connect to Neon
# ---------------------------------------
database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()


# ---------------------------------------
# 3. Load economic records
# ---------------------------------------
insert_sql = """
    INSERT INTO dim_economic
    (
        economic_date,
        unemployment_rate
    )
    VALUES (%s, %s);
"""

loaded = 0

for _, row in economic_df.iterrows():

    # FRED data normally has these columns
    if "date" in economic_df.columns:
        economic_date = row["date"]
    else:
        economic_date = row["observation_date"]

    unemployment_rate = row["unrate"]

    if pd.notna(economic_date) and pd.notna(unemployment_rate):

        cursor.execute(
            insert_sql,
            (
                economic_date,
                float(unemployment_rate)
            )
        )

        loaded += 1


# ---------------------------------------
# 4. Save changes
# ---------------------------------------
conn.commit()

print("\nEconomic data loaded successfully!")
print("Records inserted:", loaded)


# ---------------------------------------
# 5. Check warehouse
# ---------------------------------------
cursor.execute("""
    SELECT COUNT(*)
    FROM dim_economic;
""")

count = cursor.fetchone()[0]

print("Rows currently in dim_economic:", count)


cursor.close()
conn.close()

Economic records to load: 942
Columns: ['observation_date', 'unrate']

Economic data loaded successfully!
Records inserted: 942
Rows currently in dim_economic: 942

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

query = """
    SELECT
        economic_key,
        economic_date,
        unemployment_rate
    FROM dim_economic
    ORDER BY economic_date
    LIMIT 10;
"""

economic_check = pd.read_sql(query, conn)

display(economic_check)

conn.close()

/tmp/ipykernel_770/772379513.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  economic_check = pd.read_sql(query, conn)

   economic_key economic_date  unemployment_rate
0             1    1948-01-01                3.4
1             2    1948-02-01                3.8
2             3    1948-03-01                4.0
3             4    1948-04-01                3.9
4             5    1948-05-01                3.5
5             6    1948-06-01                3.6
6             7    1948-07-01                3.6
7             8    1948-08-01                3.9
8             9    1948-09-01                3.8
9            10    1948-10-01                3.7

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

# ---------------------------------------
# 1. Load processed sales data
# ---------------------------------------
sales_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/sales/sales_clean.csv"
)

sales_df = pd.read_csv(sales_path)

print("Sales columns:")
print(list(sales_df.columns))

# ---------------------------------------
# 2. Find the sales date column
# ---------------------------------------
possible_date_columns = [
    "saledate",
    "sale_date",
    "date"
]

date_column = None

for column in possible_date_columns:
    if column in sales_df.columns:
        date_column = column
        break

if date_column is None:
    raise ValueError(
        "Could not find a sales date column."
    )

print("Using date column:", date_column)

# ---------------------------------------
# 3. Convert dates
# ---------------------------------------
sales_df[date_column] = pd.to_datetime(
    sales_df[date_column],
    errors="coerce"
)

sales_dates = (
    sales_df[date_column]
    .dropna()
    .dt.normalize()
    .drop_duplicates()
    .sort_values()
)

print("Unique sales dates:", len(sales_dates))

# ---------------------------------------
# 4. Connect to Neon
# ---------------------------------------
database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()

# ---------------------------------------
# 5. Insert dates
# ---------------------------------------
insert_sql = """
    INSERT INTO dim_date
    (
        date_key,
        full_date,
        year,
        quarter,
        month,
        month_name,
        day
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (date_key) DO NOTHING;
"""

loaded = 0

for date_value in sales_dates:

    date_value = date_value.date()

    date_key = int(date_value.strftime("%Y%m%d"))

    year = date_value.year
    quarter = ((date_value.month - 1) // 3) + 1
    month = date_value.month
    month_name = date_value.strftime("%B")
    day = date_value.day

    cursor.execute(
        insert_sql,
        (
            date_key,
            date_value,
            year,
            quarter,
            month,
            month_name,
            day
        )
    )

    loaded += 1

# ---------------------------------------
# 6. Save changes
# ---------------------------------------
conn.commit()

print("\nDate dimension loaded successfully!")
print("Dates processed:", loaded)

# ---------------------------------------
# 7. Check the warehouse
# ---------------------------------------
cursor.execute("""
    SELECT COUNT(*)
    FROM dim_date;
""")

count = cursor.fetchone()[0]

print("Rows currently in dim_date:", count)

cursor.close()
conn.close()

Sales columns:
['year', 'make', 'model', 'body', 'transmission', 'vin', 'state', 'condition', 'odometer', 'color', 'interior', 'mmr', 'sellingprice', 'saledate', 'truck']
Using date column: saledate
Unique sales dates: 66

Date dimension loaded successfully!
Dates processed: 66
Rows currently in dim_date: 66

In [ ]:
from google.colab import userdata
import psycopg2
import pandas as pd

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

query = """
    SELECT
        date_key,
        full_date,
        year,
        quarter,
        month,
        month_name,
        day
    FROM dim_date
    ORDER BY full_date
    LIMIT 10;
"""

date_check = pd.read_sql(query, conn)

display(date_check)

conn.close()

/tmp/ipykernel_770/3666813365.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  date_check = pd.read_sql(query, conn)

   date_key   full_date  year  quarter  month month_name  day
0  20141216  2014-12-16  2014        4     12   December   16
1  20141217  2014-12-17  2014        4     12   December   17
2  20141218  2014-12-18  2014        4     12   December   18
3  20141219  2014-12-19  2014        4     12   December   19
4  20141222  2014-12-22  2014        4     12   December   22
5  20141223  2014-12-23  2014        4     12   December   23
6  20141224  2014-12-24  2014        4     12   December   24
7  20141226  2014-12-26  2014        4     12   December   26
8  20141229  2014-12-29  2014        4     12   December   29
9  20141230  2014-12-30  2014        4     12   December   30

In [64]:
from google.colab import userdata
import psycopg2
import pandas as pd

# ============================================
# 1. Load processed sales data
# ============================================

sales_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/sales/sales_clean.csv"
)

sales_df = pd.read_csv(sales_path)

print("Sales records:", len(sales_df))
print("Sales columns:")
print(list(sales_df.columns))


# ============================================
# 2. Identify important columns
# ============================================

date_column = None

for column in ["saledate", "sale_date", "date"]:
    if column in sales_df.columns:
        date_column = column
        break

if date_column is None:
    raise ValueError("Sales date column was not found.")

price_column = None

for column in ["sellingprice", "selling_price", "price"]:
    if column in sales_df.columns:
        price_column = column
        break

if price_column is None:
    raise ValueError("Sales price column was not found.")

mileage_column = None

for column in ["odometer", "mileage"]:
    if column in sales_df.columns:
        mileage_column = column
        break

print("\nDate column:", date_column)
print("Price column:", price_column)
print("Mileage column:", mileage_column)


# ============================================
# 3. Convert data types
# ============================================

sales_df[date_column] = pd.to_datetime(
    sales_df[date_column],
    errors="coerce"
)

sales_df[price_column] = pd.to_numeric(
    sales_df[price_column],
    errors="coerce"
)

if mileage_column:
    sales_df[mileage_column] = pd.to_numeric(
        sales_df[mileage_column],
        errors="coerce"
    )


# ============================================
# 4. Connect to Neon
# ============================================

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)
cursor = conn.cursor()


# ============================================
# 5. Load sales records
# ============================================

insert_sql = """
    INSERT INTO fact_sales
    (
        dealer_key,
        vehicle_key,
        date_key,
        selling_price,
        odometer
    )
    VALUES (%s, %s, %s, %s, %s);
"""

loaded = 0
skipped = 0

for _, row in sales_df.iterrows():

    sale_date = row[date_column]

    if pd.isna(sale_date):
        skipped += 1
        continue

    # Create warehouse date key
    sale_date = sale_date.date()

    date_key = int(
        sale_date.strftime("%Y%m%d")
    )

    selling_price = row[price_column]

    if pd.isna(selling_price):
        skipped += 1
        continue

    selling_price = float(selling_price)

    # Mileage
    odometer = None

    if mileage_column:
        if pd.notna(row[mileage_column]):
            odometer = int(row[mileage_column])

    # Dealer is NULL because the sales source
    # does not provide our dealer_id.
    dealer_key = None

    # Try to match vehicle using make + model
    vehicle_key = None

    if "make" in sales_df.columns and "model" in sales_df.columns:

        make = row["make"]
        model = row["model"]

        if pd.notna(make) and pd.notna(model):

            cursor.execute(
                """
                SELECT vehicle_key
                FROM dim_vehicle
                WHERE LOWER(make) = LOWER(%s)
                  AND LOWER(model) = LOWER(%s)
                LIMIT 1;
                """,
                (
                    str(make).strip(),
                    str(model).strip()
                )
            )

            result = cursor.fetchone()

            if result:
                vehicle_key = result[0]

    cursor.execute(
        insert_sql,
        (
            dealer_key,
            vehicle_key,
            date_key,
            selling_price,
            odometer
        )
    )

    loaded += 1


# ============================================
# 6. Commit
# ============================================

conn.commit()

print("\nSales loading completed!")
print("Sales records loaded:", loaded)
print("Sales records skipped:", skipped)


# ============================================
# 7. Check warehouse
# ============================================

cursor.execute("""
    SELECT COUNT(*)
    FROM fact_sales;
""")

count = cursor.fetchone()[0]

print("Rows currently in fact_sales:", count)

cursor.close()
conn.close()

Sales records: 402928
Sales columns:
['year', 'make', 'model', 'body', 'transmission', 'vin', 'state', 'condition', 'odometer', 'color', 'interior', 'mmr', 'sellingprice', 'saledate', 'truck']

Date column: saledate
Price column: sellingprice
Mileage column: odometer

KeyboardInterrupt:

In [65]:
from google.colab import userdata
import psycopg2
from psycopg2.extras import execute_values
import pandas as pd

# ============================================
# 1. Load the 402,928 sales records
# ============================================

sales_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/sales/sales_clean.csv"
)

sales_df = pd.read_csv(sales_path)

print("Sales records:", len(sales_df))

# ============================================
# 2. Prepare columns
# ============================================

sales_df["saledate"] = pd.to_datetime(
    sales_df["saledate"],
    errors="coerce"
)

sales_df["sellingprice"] = pd.to_numeric(
    sales_df["sellingprice"],
    errors="coerce"
)

sales_df["odometer"] = pd.to_numeric(
    sales_df["odometer"],
    errors="coerce"
)

# Remove rows without required values
sales_df = sales_df.dropna(
    subset=["saledate", "sellingprice"]
).copy()

# Create warehouse date key
sales_df["date_key"] = (
    sales_df["saledate"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

# ============================================
# 3. Make sure all sales dates exist
#    in dim_date
# ============================================

database_url = userdata.get("NEON_DATABASE_URL")

if not database_url:
    raise ValueError(
        "NEON_DATABASE_URL was not found. "
        "Check Colab Secrets and Notebook access."
    )

conn = psycopg2.connect(database_url)
cursor = conn.cursor()

# Get existing date keys
cursor.execute("""
    SELECT date_key
    FROM dim_date;
""")

existing_dates = {
    row[0]
    for row in cursor.fetchall()
}

# Create missing dates
missing_dates = (
    sales_df[
        ~sales_df["date_key"].isin(existing_dates)
    ][["date_key", "saledate"]]
    .drop_duplicates("date_key")
)

if len(missing_dates) > 0:

    date_rows = []

    for _, row in missing_dates.iterrows():

        d = row["saledate"].date()

        date_rows.append(
            (
                int(row["date_key"]),
                d,
                d.year,
                ((d.month - 1) // 3) + 1,
                d.month,
                d.strftime("%B"),
                d.day
            )
        )

    execute_values(
        cursor,
        """
        INSERT INTO dim_date
        (
            date_key,
            full_date,
            year,
            quarter,
            month,
            month_name,
            day
        )
        VALUES %s
        ON CONFLICT (date_key) DO NOTHING;
        """,
        date_rows,
        page_size=1000
    )

    print(
        "Added missing dates:",
        len(date_rows)
    )

# ============================================
# 4. Prepare sales records for bulk loading
# ============================================

sales_rows = []

for row in sales_df.itertuples(index=False):

    odometer = (
        None
        if pd.isna(row.odometer)
        else int(row.odometer)
    )

    sales_rows.append(
        (
            None,                    # dealer_key
            None,                    # vehicle_key
            int(row.date_key),
            float(row.sellingprice),
            odometer
        )
    )

print(
    "Prepared records for loading:",
    len(sales_rows)
)

# ============================================
# 5. Bulk insert into fact_sales
# ============================================

print("Loading sales into PostgreSQL...")

execute_values(
    cursor,
    """
    INSERT INTO fact_sales
    (
        dealer_key,
        vehicle_key,
        date_key,
        selling_price,
        odometer
    )
    VALUES %s;
    """,
    sales_rows,
    page_size=5000
)

# ============================================
# 6. Commit
# ============================================

conn.commit()

print("Sales data loaded successfully!")

# ============================================
# 7. Verify
# ============================================

cursor.execute("""
    SELECT COUNT(*)
    FROM fact_sales;
""")

count = cursor.fetchone()[0]

print(
    "Rows currently in fact_sales:",
    count
)

cursor.close()
conn.close()

Sales records: 402928
Prepared records for loading: 402928
Loading sales into PostgreSQL...
Sales data loaded successfully!
Rows currently in fact_sales: 402928

In [66]:
from google.colab import userdata
import psycopg2
import pandas as pd

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

# ---------------------------------------
# 1. Count sales
# ---------------------------------------

count_query = """
SELECT COUNT(*) AS total_sales
FROM fact_sales;
"""

count_df = pd.read_sql(count_query, conn)

print("Total sales in warehouse:")
display(count_df)


# ---------------------------------------
# 2. Calculate sales revenue
# ---------------------------------------

revenue_query = """
SELECT
    COUNT(*) AS number_of_sales,
    SUM(selling_price) AS total_revenue,
    AVG(selling_price) AS average_sale_price,
    MIN(selling_price) AS minimum_sale_price,
    MAX(selling_price) AS maximum_sale_price
FROM fact_sales;
"""

revenue_df = pd.read_sql(revenue_query, conn)

print("Sales summary:")
display(revenue_df)


# ---------------------------------------
# 3. Show sample records
# ---------------------------------------

sample_query = """
SELECT
    sales_key,
    dealer_key,
    vehicle_key,
    date_key,
    selling_price,
    odometer
FROM fact_sales
ORDER BY sales_key
LIMIT 10;
"""

sample_df = pd.read_sql(sample_query, conn)

print("Sample sales:")
display(sample_df)


conn.close()

Total sales in warehouse:

/tmp/ipykernel_770/2257675696.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count_df = pd.read_sql(count_query, conn)

   total_sales
0       402928

/tmp/ipykernel_770/2257675696.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  revenue_df = pd.read_sql(revenue_query, conn)

Sales summary:

,number_of_sales,total_revenue,average_sale_price,minimum_sale_price,maximum_sale_price
0,402928,5.307264e+09,13171.742562,1.0,230000.0

Sample sales:

/tmp/ipykernel_770/2257675696.py:61: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sample_df = pd.read_sql(sample_query, conn)

   sales_key dealer_key vehicle_key  date_key  selling_price  odometer
0      41852       None        None  20141216        21500.0     16639
1      41853       None        None  20141216        21500.0      9393
2      41854       None        None  20150115        30000.0      1331
3      41855       None        None  20150129        27750.0     14282
4      41856       None        None  20141218        67000.0      2641
5      41857       None        None  20141230        10900.0      5554
6      41858       None        None  20141217        65000.0     14943
7      41859       None        None  20141216         9800.0     28617
8      41860       None        None  20141218        32250.0      9557
9      41861       None        None  20150120        17500.0      4809

In [67]:
from google.colab import userdata
import psycopg2
from psycopg2.extras import execute_values
import pandas as pd

# ============================================
# 1. Load processed repair data
# ============================================

repair_path = (
    "/content/toyotadrive-data-platform/"
    "data/processed/repairs/repairs_clean.csv"
)

repairs_df = pd.read_csv(repair_path)

print("Repair records:", len(repairs_df))
print("Repair columns:")
print(list(repairs_df.columns))


# ============================================
# 2. Find repair date column
# ============================================

date_column = None

for column in [
    "repair_date",
    "service_date",
    "date",
    "saledate"
]:
    if column in repairs_df.columns:
        date_column = column
        break

if date_column is None:
    raise ValueError(
        "Could not find a repair date column. "
        "Available columns: "
        + str(list(repairs_df.columns))
    )


# ============================================
# 3. Find repair cost column
# ============================================

cost_column = None

for column in [
    "repair_cost",
    "cost",
    "total",
    "price"
]:
    if column in repairs_df.columns:
        cost_column = column
        break

if cost_column is None:
    raise ValueError(
        "Could not find a repair cost column. "
        "Available columns: "
        + str(list(repairs_df.columns))
    )


# ============================================
# 4. Find mileage column
# ============================================

mileage_column = None

for column in [
    "mileage",
    "odometer"
]:
    if column in repairs_df.columns:
        mileage_column = column
        break


print("\nUsing:")
print("Date:", date_column)
print("Cost:", cost_column)
print("Mileage:", mileage_column)


# ============================================
# 5. Clean required fields
# ============================================

repairs_df[date_column] = pd.to_datetime(
    repairs_df[date_column],
    errors="coerce"
)

repairs_df[cost_column] = pd.to_numeric(
    repairs_df[cost_column],
    errors="coerce"
)

if mileage_column:
    repairs_df[mileage_column] = pd.to_numeric(
        repairs_df[mileage_column],
        errors="coerce"
    )

repairs_df = repairs_df.dropna(
    subset=[date_column, cost_column]
).copy()


# ============================================
# 6. Connect to Neon
# ============================================

database_url = userdata.get("NEON_DATABASE_URL")

if not database_url:
    raise ValueError(
        "NEON_DATABASE_URL was not found."
    )

conn = psycopg2.connect(database_url)
cursor = conn.cursor()


# ============================================
# 7. Prepare repair records
# ============================================

repair_rows = []

for row in repairs_df.itertuples(index=False):

    repair_date = getattr(
        row,
        date_column
    ).date()

    repair_cost = float(
        getattr(row, cost_column)
    )

    mileage = None

    if mileage_column:

        mileage_value = getattr(
            row,
            mileage_column
        )

        if pd.notna(mileage_value):
            mileage = int(mileage_value)

    repair_rows.append(
        (
            None,          # dealer_key
            None,          # vehicle_key
            repair_date,
            repair_cost,
            mileage
        )
    )


print(
    "\nPrepared repair records:",
    len(repair_rows)
)


# ============================================
# 8. Bulk insert into fact_repairs
# ============================================

print("Loading repairs into PostgreSQL...")

execute_values(
    cursor,
    """
    INSERT INTO fact_repairs
    (
        dealer_key,
        vehicle_key,
        repair_date,
        repair_cost,
        mileage
    )
    VALUES %s;
    """,
    repair_rows,
    page_size=5000
)


# ============================================
# 9. Commit
# ============================================

conn.commit()

print("Repair data loaded successfully!")


# ============================================
# 10. Verify row count
# ============================================

cursor.execute("""
    SELECT COUNT(*)
    FROM fact_repairs;
""")

count = cursor.fetchone()[0]

print(
    "Rows currently in fact_repairs:",
    count
)

cursor.close()
conn.close()

Repair records: 1
Repair columns:
['date', 'tickettype', 'total', 'mileage', 'modyear', 'make', 'model']

Using:
Date: date
Cost: total
Mileage: mileage

Prepared repair records: 1
Loading repairs into PostgreSQL...
Repair data loaded successfully!
Rows currently in fact_repairs: 1

In [68]:
from google.colab import userdata
import psycopg2
import pandas as pd

# Connect to Neon
database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

# ---------------------------------------
# Check all warehouse tables
# ---------------------------------------

tables = [
    "dim_dealer",
    "dim_vehicle",
    "dim_date",
    "dim_economic",
    "fact_sales",
    "fact_repairs"
]

results = []

for table in tables:

    query = f"""
        SELECT COUNT(*) AS row_count
        FROM {table};
    """

    count = pd.read_sql(query, conn).iloc[0]["row_count"]

    results.append({
        "table_name": table,
        "row_count": int(count)
    })

warehouse_check = pd.DataFrame(results)

display(warehouse_check)

conn.close()

/tmp/ipykernel_770/2820196109.py:32: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql(query, conn).iloc[0]["row_count"]

     table_name  row_count
0    dim_dealer          5
1   dim_vehicle         18
2      dim_date         66
3  dim_economic        942
4    fact_sales     402928
5  fact_repairs          1

In [69]:
from google.colab import userdata
import psycopg2
import pandas as pd

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

query = """
SELECT
    d.year,
    d.month_name,
    COUNT(f.sales_key) AS vehicles_sold,
    ROUND(
        SUM(f.selling_price)::numeric,
        2
    ) AS total_sales_revenue,
    ROUND(
        AVG(f.selling_price)::numeric,
        2
    ) AS average_vehicle_price
FROM fact_sales f
JOIN dim_date d
    ON f.date_key = d.date_key
GROUP BY
    d.year,
    d.month,
    d.month_name
ORDER BY
    d.year,
    d.month;
"""

monthly_sales = pd.read_sql(
    query,
    conn
)

display(monthly_sales)

conn.close()

/tmp/ipykernel_770/3852150246.py:34: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  monthly_sales = pd.read_sql(

   year month_name  vehicles_sold  total_sales_revenue  average_vehicle_price
0  2014   December          53520         6.044342e+08               11293.61
1  2015    January         140609         1.868476e+09               13288.45
2  2015   February         163052         2.218852e+09               13608.25
3  2015      March          45747         6.155011e+08               13454.46

In [70]:
from google.colab import userdata
import psycopg2
import pandas as pd

database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

query = """
SELECT
    COUNT(*) AS total_repairs,
    ROUND(
        SUM(repair_cost)::numeric,
        2
    ) AS total_repair_revenue,
    ROUND(
        AVG(repair_cost)::numeric,
        2
    ) AS average_repair_cost
FROM fact_repairs;
"""

repair_kpis = pd.read_sql(
    query,
    conn
)

display(repair_kpis)

conn.close()

/tmp/ipykernel_770/3546840597.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  repair_kpis = pd.read_sql(

   total_repairs  total_repair_revenue  average_repair_cost
0              1                   5.0                  5.0

In [71]:
from google.colab import userdata
import psycopg2
import pandas as pd

# Connect to Neon
database_url = userdata.get("NEON_DATABASE_URL")

conn = psycopg2.connect(database_url)

# ============================================
# 1. Management KPIs
# ============================================

kpi_query = """
SELECT
    (SELECT COUNT(*) FROM fact_sales) AS vehicles_sold,

    (SELECT ROUND(SUM(selling_price)::numeric, 2)
     FROM fact_sales) AS sales_revenue,

    (SELECT ROUND(AVG(selling_price)::numeric, 2)
     FROM fact_sales) AS average_vehicle_price,

    (SELECT COUNT(*) FROM fact_repairs) AS total_repairs,

    (SELECT ROUND(SUM(repair_cost)::numeric, 2)
     FROM fact_repairs) AS repair_revenue,

    (SELECT ROUND(AVG(repair_cost)::numeric, 2)
     FROM fact_repairs) AS average_repair_cost;
"""

kpi_df = pd.read_sql(kpi_query, conn)

print("MANAGEMENT KPIs")
display(kpi_df)


# ============================================
# 2. Monthly Sales
# ============================================

monthly_sales_query = """
SELECT
    d.year,
    d.month,
    d.month_name,
    COUNT(f.sales_key) AS vehicles_sold,
    ROUND(SUM(f.selling_price)::numeric, 2) AS revenue,
    ROUND(AVG(f.selling_price)::numeric, 2) AS average_price
FROM fact_sales f
JOIN dim_date d
    ON f.date_key = d.date_key
GROUP BY
    d.year,
    d.month,
    d.month_name
ORDER BY
    d.year,
    d.month;
"""

monthly_sales_df = pd.read_sql(
    monthly_sales_query,
    conn
)

print("MONTHLY SALES")
display(monthly_sales_df.head(20))


# ============================================
# 3. Sales by Vehicle
# ============================================

vehicle_sales_query = """
SELECT
    v.make,
    v.model,
    COUNT(f.sales_key) AS vehicles_sold,
    ROUND(SUM(f.selling_price)::numeric, 2) AS revenue
FROM fact_sales f
LEFT JOIN dim_vehicle v
    ON f.vehicle_key = v.vehicle_key
GROUP BY
    v.make,
    v.model
ORDER BY
    revenue DESC;
"""

vehicle_sales_df = pd.read_sql(
    vehicle_sales_query,
    conn
)

print("SALES BY VEHICLE")
display(vehicle_sales_df.head(20))


# ============================================
# 4. Monthly Repairs
# ============================================

repair_query = """
SELECT
    EXTRACT(YEAR FROM repair_date)::integer AS year,
    EXTRACT(MONTH FROM repair_date)::integer AS month,
    COUNT(*) AS repairs,
    ROUND(SUM(repair_cost)::numeric, 2) AS repair_revenue,
    ROUND(AVG(repair_cost)::numeric, 2) AS average_repair_cost
FROM fact_repairs
GROUP BY
    EXTRACT(YEAR FROM repair_date),
    EXTRACT(MONTH FROM repair_date)
ORDER BY
    year,
    month;
"""

repair_df = pd.read_sql(
    repair_query,
    conn
)

print("REPAIR PERFORMANCE")
display(repair_df.head(20))


# ============================================
# Close connection
# ============================================

conn.close()

print("Dashboard datasets created successfully!")

/tmp/ipykernel_770/388952503.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  kpi_df = pd.read_sql(kpi_query, conn)

MANAGEMENT KPIs

,vehicles_sold,sales_revenue,average_vehicle_price,total_repairs,repair_revenue,average_repair_cost
0,402928,5.307264e+09,13171.74,1,5.0,5.0

/tmp/ipykernel_770/388952503.py:63: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  monthly_sales_df = pd.read_sql(

MONTHLY SALES

   year  month month_name  vehicles_sold       revenue  average_price
0  2014     12   December          53520  6.044342e+08       11293.61
1  2015      1    January         140609  1.868476e+09       13288.45
2  2015      2   February         163052  2.218852e+09       13608.25
3  2015      3      March          45747  6.155011e+08       13454.46

SALES BY VEHICLE

/tmp/ipykernel_770/388952503.py:92: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vehicle_sales_df = pd.read_sql(

   make model  vehicles_sold       revenue
0  None  None         402928  5.307264e+09

/tmp/ipykernel_770/388952503.py:121: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  repair_df = pd.read_sql(

REPAIR PERFORMANCE

   year  month  repairs  repair_revenue  average_repair_cost
0  2002     10        1             5.0                  5.0

Dashboard datasets created successfully!

In [72]:
# Create a folder for dashboard data

import os

dashboard_path = (
    "/content/toyotadrive-data-platform/"
    "dashboard/data"
)

os.makedirs(dashboard_path, exist_ok=True)

# Save dashboard datasets
kpi_df.to_csv(
    f"{dashboard_path}/kpi_summary.csv",
    index=False
)

monthly_sales_df.to_csv(
    f"{dashboard_path}/monthly_sales.csv",
    index=False
)

vehicle_sales_df.to_csv(
    f"{dashboard_path}/vehicle_sales.csv",
    index=False
)

repair_df.to_csv(
    f"{dashboard_path}/repair_performance.csv",
    index=False
)

print("Dashboard datasets saved successfully!")

print("\nFiles created:")

for file in os.listdir(dashboard_path):
    print("-", file)

Dashboard datasets saved successfully!

Files created:
- vehicle_sales.csv
- kpi_summary.csv
- monthly_sales.csv
- repair_performance.csv

In [73]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display

# ============================================
# 1. Load dashboard datasets
# ============================================

dashboard_path = (
    "/content/toyotadrive-data-platform/"
    "dashboard/data"
)

kpi_df = pd.read_csv(
    f"{dashboard_path}/kpi_summary.csv"
)

monthly_sales_df = pd.read_csv(
    f"{dashboard_path}/monthly_sales.csv"
)

vehicle_sales_df = pd.read_csv(
    f"{dashboard_path}/vehicle_sales.csv"
)

repair_df = pd.read_csv(
    f"{dashboard_path}/repair_performance.csv"
)

print("Dashboard data loaded successfully!")

Dashboard data loaded successfully!

In [74]:
# ============================================
# MONTHLY SALES TREND
# ============================================

monthly_sales_df["period"] = (
    monthly_sales_df["year"].astype(str)
    + "-"
    + monthly_sales_df["month"].astype(str).str.zfill(2)
)

fig = px.line(
    monthly_sales_df,
    x="period",
    y="revenue",
    markers=True,
    title="Monthly Vehicle Sales Revenue"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue ($)"
)

fig.show()

In [75]:
# ============================================
# TOP VEHICLES BY SALES
# ============================================

top_vehicles = (
    vehicle_sales_df
    .dropna(subset=["make", "model"])
    .sort_values(
        "revenue",
        ascending=False
    )
    .head(15)
    .copy()
)

top_vehicles["vehicle"] = (
    top_vehicles["make"].astype(str)
    + " "
    + top_vehicles["model"].astype(str)
)

fig = px.bar(
    top_vehicles.sort_values("revenue"),
    x="revenue",
    y="vehicle",
    orientation="h",
    title="Top 15 Vehicle Models by Revenue",
    color="revenue",
    color_continuous_scale="Blues"
)

fig.update_layout(
    xaxis_title="Revenue ($)",
    yaxis_title="Vehicle"
)

fig.show()

In [76]:
# ============================================
# MONTHLY REPAIR REVENUE
# ============================================

repair_df["period"] = (
    repair_df["year"].astype(str)
    + "-"
    + repair_df["month"].astype(str).str.zfill(2)
)

fig = px.bar(
    repair_df,
    x="period",
    y="repair_revenue",
    title="Monthly Repair Revenue",
    color="repair_revenue",
    color_continuous_scale="Greens"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Repair Revenue ($)"
)

fig.show()

In [77]:
# ============================================
# SALES VS REPAIR PERFORMANCE
# ============================================

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=monthly_sales_df["period"],
        y=monthly_sales_df["revenue"],
        mode="lines+markers",
        name="Vehicle Sales Revenue"
    )
)

fig.update_layout(
    title="Vehicle Sales Revenue Trend",
    xaxis_title="Month",
    yaxis_title="Revenue ($)",
    hovermode="x unified"
)

fig.show()